name: Test actions crypto
on: [push]

jobs:
  local_repo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo abc > test.file
      - name: Hello world
        uses: ./
        with:
          crypto-path: test.file
          crypto-action: enc
          crypto-password: 123456
      - name: check enc
        run: cat test.file.enc
      - name: dec
        uses: ./
        with:
          crypto-path: test.file.enc
          crypto-action: dec
          crypto-password: 123456
      - name: check enc
        run: cat test.file
        
